spring:
  profiles:
    active: "Local"
  main:
    banner-mode: "off"    

---

spring:
    profiles: Local
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: <full url with schema name>
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.tomcat.max-wait: 10000
spring.datasource.tomcat.max-active: 1000
spring.datasource.tomcat.test-on-borrow: true
server.port: 9097
